# TODO
import sys
from pathlib import Path
from snakemake.utils import min_version
import subprocess

# Set minimum version of snakemake to work with
min_version("8.20")


# Load configuration files
configfile: "config/config.yaml"
configfile: "config/target.yaml"

# Read target directory and set working tree
TARGET_DIR = Path(config["target_dir"])
PREFIX = config["prefix"]
OUTDIR = Path(config["outdir"])
PATHFIXCORE = Path(OUTFIR/"PREPROCESING")
PATHALN = Path(PATHFIXCORE/"ALN")
PATHCONS = Path(PATHFIXCORE/"CONS")
PATHCURATED = Path(OUTDIR/"DEF_GENES")
PATHPHYLO = Path(OUTDIR/"PHYLO")

# Create directories
directories = [OUTDIR, PATHFIXCORE, PATHALN, PATHCONS, PATHCURATED, PATHPHYLO]
for directory in directories:
    directory.mkdir(parents=True, exist_ok=True)


# Include rules
TODO

# Set final file
rule all:
    input:
        OUTDIR/f"tree/{PREFIX}.treefile"