TRIMAL_PCT:
  0.8

MAFFT:
  N_CORES:
    8

PROKKA:
  N_CORES:
    8

SEQKIT:
  N_CORES:
    8
    
IQTREE:
  EVO_MODEL:
    "GTR+G"
  BOOTSTRAP:
    1000
  N_CORES:
    8

PRUNE_TREES:
  MAX_MISSING: 0.15
  MAX_CONSECUTIVE_VARIANTS: 3

CORE:
  N_CORES: 32
  TOOL: "none"
  THRESHOLD: 0.90
  ROARY:
    FAMILY_THRESHOLD: 95
    EXTRA_PARAMS: ""
  PANAROO: 
    FAMILY_THRESHOLD: 0.7
    EXTRA_PARAMS: ""
    CLEAN_MODE: "sensitive"
  PANACOTA:
    FAMILY_THRESHOLD: 0.8