name: Install

on: [push, pull_request]

jobs:

  skip_duplicates:
      permissions:
        actions: write
        contents: read
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          cancel_others: 'true'
          concurrent_skipping: 'same_content_newer'
          
  Install:  
    needs: skip_duplicates
    if: ${{ needs.skip_duplicate.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    uses: snakemake/snakemake-github-action@v1
    with:
      directory: '.test'
      snakefile: 'workflow/Snakefile'
      args: '--configfile config/config.yaml .test/targets.yaml --conda-create-envs-only --use-conda -c1'


